package com.ecodala.core.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf
import com.ecodala.core.domain.model.ChallengeStatus
import com.ecodala.core.domain.model.ChallengeType
import com.ecodala.core.domain.model.WasteType

data class EcoStrings(
    val languageTag: String,
    val home: String,
    val map: String,
    val submit: String,
    val leads: String,
    val profile: String,
    val login: String,
    val splashTagline: String,
    val splashExperience: String,
    val registerNow: String,
    val createAccount: String,
    val forgotPassword: String,
    val welcomeBack: String,
    val signInSubtitle: String,
    val emailAddress: String,
    val password: String,
    val continueWithGoogle: String,
    val or: String,
    val noAccountPrefix: String,
    val fullName: String,
    val joinCommunity: String,
    val confirmPassword: String,
    val fairlyStrongPassword: String,
    val termsPrefix: String,
    val terms: String,
    val termsAnd: String,
    val privacyPolicy: String,
    val orSignUpWith: String,
    val alreadyHaveAccount: String,
    val checkYourEmail: String,
    val forgotPasswordSubtitle: String,
    val resetInstructions: (String) -> String,
    val rememberedPassword: String,
    val sendResetLink: String,
    val resetLinkSent: String,
    val invalidEmail: String,
    val hello: (String) -> String,
    val quickActions: String,
    val currentEcoRating: String,
    val points: (Int) -> String,
    val pointsLabel: String,
    val level: (Int) -> String,
    val globalRank: (Int) -> String,
    val virtualTreeTitle: String,
    val progressToLevel: (Int, Int) -> String,
    val recentAchievements: String,
    val searchLocation: String,
    val openUntil: String,
    val distanceAway: (Double, Int) -> String,
    val acceptedItems: String,
    val reward: String,
    val acceptedWasteTypes: String,
    val open: String,
    val buildRoute: String,
    val call: String,
    val share: String,
    val sustainableFact: String,
    val submitWaste: String,
    val wasteType: String,
    val quantity: String,
    val photoConfirmation: String,
    val takePhotoUpload: String,
    val commentOptional: String,
    val addNote: String,
    val submitWithPoints: (Int) -> String,
    val myEcoTree: String,
    val progressToNextLevel: (Int) -> String,
    val xpStatus: (Int, Int) -> String,
    val xpToGo: (Int) -> String,
    val nextGoal: String,
    val collectXpGoal: (Int, Int) -> String,
    val growthHistory: String,
    val challenges: String,
    val daily: String,
    val weekly: String,
    val special: String,
    val dailyChallenges: String,
    val weeklyChallenges: String,
    val left: (Int) -> String,
    val active: String,
    val completed: String,
    val locked: String,
    val ecoSpecialTitle: String,
    val ecoSpecialSubtitle: String,
    val leaderboard: String,
    val students: String,
    val faculties: String,
    val topFaculty: String,
    val thisWeek: (Int) -> String,
    val total: String,
    val members: String,
    val topContributor: (Int, String) -> String,
    val memberSince: (String) -> String,
    val kgWaste: String,
    val trees: String,
    val sustainabilityScore: String,
    val topContributorText: String,
    val nextMilestone: String,
    val myAchievements: String,
    val recyclingHistory: String,
    val notifications: String,
    val settings: String,
    val support: String,
    val logout: String,
    val all: String,
    val achievements: String,
    val ecoProgress: String,
    val achievementsUnlocked: (Int, Int) -> String,
    val completePercent: (Int) -> String,
    val recentSubmissions: String,
    val yourImpact: String,
    val impactSubtitle: String,
    val recentNotifications: String,
    val unread: (Int) -> String,
    val totalUpdates: (Int) -> String,
    val markAllRead: String,
    val supportHeroTitle: String,
    val supportHeroSubtitle: String,
    val contactUs: String,
    val sendRequest: String,
    val describeIssue: String,
    val requestSaved: String,
    val faq: String,
    val settingsPreferences: String,
    val settingsPushNotifications: String,
    val settingsPushNotificationsSubtitle: String,
    val settingsLocation: String,
    val settingsLocationSubtitle: String,
    val settingsAiTips: String,
    val settingsAiTipsSubtitle: String,
    val settingsDisplayUnits: String,
    val settingsDarkMode: String,
    val settingsDarkModeSubtitle: String,
    val settingsLanguage: String,
    val settingsLanguageSubtitle: String,
    val settingsPreferredUnit: String,
    val settingsPreferredUnitSubtitle: String,
    val settingsPrivacy: String,
    val settingsPublicProfile: String,
    val settingsPublicProfileSubtitle: String,
    val settingsDataSecurity: String,
    val settingsDataSecuritySubtitle: String,
    val settingsInfo: String,
    val wasteTypeName: (WasteType) -> String,
    val challengeTypeName: (ChallengeType) -> String,
    val challengeStatusName: (ChallengeStatus) -> String
)

val LocalEcoStrings = staticCompositionLocalOf { englishEcoStrings }

@Composable
fun EcoLocalization(
    languageTag: String,
    content: @Composable () -> Unit
) {
    CompositionLocalProvider(
        LocalEcoStrings provides ecoStringsFor(languageTag),
        content = content
    )
}

fun ecoStringsFor(languageTag: String): EcoStrings {
    return when (languageTag) {
        "ru" -> russianEcoStrings
        "kk" -> kazakhEcoStrings
        else -> englishEcoStrings
    }
}

private val englishEcoStrings = EcoStrings(
    languageTag = "en",
    home = "Home",
    map = "Map",
    submit = "Submit",
    leads = "Leads",
    profile = "Profile",
    login = "Login",
    splashTagline = "Recycle • Track • Grow",
    splashExperience = "ECO-CONSCIOUS DIGITAL EXPERIENCE",
    registerNow = "Register Now",
    createAccount = "Create Account",
    forgotPassword = "Forgot Password?",
    welcomeBack = "Welcome Back",
    signInSubtitle = "Sign in to continue your eco journey",
    emailAddress = "Email address",
    password = "Password",
    continueWithGoogle = "Continue with Google",
    or = "or",
    noAccountPrefix = "Don't have an account? ",
    fullName = "Full Name",
    joinCommunity = "Join the eco community",
    confirmPassword = "Confirm Password",
    fairlyStrongPassword = "Fairly strong password",
    termsPrefix = "I agree to the ",
    terms = "Terms of Service",
    termsAnd = " and ",
    privacyPolicy = "Privacy Policy.",
    orSignUpWith = "OR SIGN UP WITH",
    alreadyHaveAccount = "Already have an account? ",
    checkYourEmail = "Check Your Email",
    forgotPasswordSubtitle = "Enter your email and we will send you a secure reset link.",
    resetInstructions = { "We sent password reset instructions to $it." },
    rememberedPassword = "Remembered your password? ",
    sendResetLink = "Send Reset Link",
    resetLinkSent = "Reset link sent",
    invalidEmail = "Enter a valid email address",
    hello = { "Hello, $it!" },
    quickActions = "QUICK ACTIONS",
    currentEcoRating = "CURRENT ECO RATING",
    points = { "$it pts" },
    pointsLabel = "Points",
    level = { "Level $it" },
    globalRank = { "  Global Rank: #$it" },
    virtualTreeTitle = "Your Virtual Tree",
    progressToLevel = { progress, level -> "$progress% to Level $level" },
    recentAchievements = "Recent Achievements",
    searchLocation = "Search location...",
    openUntil = "Open until 8:00 PM",
    distanceAway = { rating, meters -> " $rating (124)  •  $meters m away" },
    acceptedItems = "Accepted Items",
    reward = "Reward",
    acceptedWasteTypes = "Accepted Waste Types",
    open = "OPEN",
    buildRoute = "Build Route",
    call = "Call",
    share = "Share",
    sustainableFact = "Sustainable Fact",
    submitWaste = "Submit Waste",
    wasteType = "Waste Type",
    quantity = "Quantity",
    photoConfirmation = "Photo Confirmation",
    takePhotoUpload = "Take Photo or Upload",
    commentOptional = "Comment (optional)",
    addNote = "Add a note...",
    submitWithPoints = { "Submit +$it pts" },
    myEcoTree = "My Eco Tree",
    progressToNextLevel = { "Progress to Level $it" },
    xpStatus = { current, next -> "$current / $next XP" },
    xpToGo = { "$it XP to go" },
    nextGoal = "Next Goal",
    collectXpGoal = { xp, level -> "Collect $xp more XP to reach Level $level" },
    growthHistory = "Growth History",
    challenges = "Challenges",
    daily = "Daily",
    weekly = "Weekly",
    special = "Special",
    dailyChallenges = "Daily Challenges",
    weeklyChallenges = "Weekly Challenges",
    left = { "$it left" },
    active = "Active",
    completed = "Completed",
    locked = "Locked",
    ecoSpecialTitle = "Eco-Special: Park Clean-up",
    ecoSpecialSubtitle = "Join the community this Saturday for double points!",
    leaderboard = "Leaderboard",
    students = "Students",
    faculties = "Faculties",
    topFaculty = "Top Faculty",
    thisWeek = { "+$it% this week" },
    total = "Total",
    members = "Members",
    topContributor = { members, name -> "$members members • Top: $name" },
    memberSince = { "Member since $it" },
    kgWaste = "kg Waste",
    trees = "Trees",
    sustainabilityScore = "Sustainability Score",
    topContributorText = "You're in the top 12%\nof contributors this\nmonth!",
    nextMilestone = "Next Milestone: Level 5",
    myAchievements = "My Achievements",
    recyclingHistory = "Recycling History",
    notifications = "Notifications",
    settings = "Settings",
    support = "Support",
    logout = "Logout",
    all = "All",
    achievements = "Achievements",
    ecoProgress = "Eco Progress",
    achievementsUnlocked = { unlocked, total -> "$unlocked of $total achievements unlocked" },
    completePercent = { "$it% complete" },
    recentSubmissions = "Recent Submissions",
    yourImpact = "Your Impact",
    impactSubtitle = "Track what you recycled and how many points you earned.",
    recentNotifications = "Recent Notifications",
    unread = { "$it unread" },
    totalUpdates = { "$it total updates from EcoDala" },
    markAllRead = "Mark all read",
    supportHeroTitle = "EcoDala Kazakhstan Care",
    supportHeroSubtitle = "We help with points, recycling places and app issues across Kazakhstan.",
    contactUs = "Contact us",
    sendRequest = "Send a request",
    describeIssue = "Describe your issue...",
    requestSaved = "Request saved. Support will contact you soon.",
    faq = "FAQ",
    settingsPreferences = "Preferences",
    settingsPushNotifications = "Push Notifications",
    settingsPushNotificationsSubtitle = "Daily challenges and reward updates",
    settingsLocation = "Location Access",
    settingsLocationSubtitle = "Show nearby recycling points",
    settingsAiTips = "AI Eco Tips",
    settingsAiTipsSubtitle = "Personalized waste sorting suggestions",
    settingsDisplayUnits = "Display & Units",
    settingsDarkMode = "Dark Mode",
    settingsDarkModeSubtitle = "Switch app theme instantly",
    settingsLanguage = "Language",
    settingsLanguageSubtitle = "Choose the app language",
    settingsPreferredUnit = "Preferred Unit",
    settingsPreferredUnitSubtitle = "Used in submissions and history",
    settingsPrivacy = "Privacy",
    settingsPublicProfile = "Public Leaderboard Profile",
    settingsPublicProfileSubtitle = "Show your name in rankings",
    settingsDataSecurity = "Data & Security",
    settingsDataSecuritySubtitle = "Account protection and data export",
    settingsInfo = "Settings are stored locally with DataStore and can be synced with the backend later.",
    wasteTypeName = { it.title },
    challengeTypeName = { it.name },
    challengeStatusName = {
        when (it) {
            ChallengeStatus.Active -> "Active"
            ChallengeStatus.Completed -> "Completed"
            ChallengeStatus.Locked -> "Locked"
        }
    }
)

private val russianEcoStrings = englishEcoStrings.copy(
    languageTag = "ru",
    home = "Главная",
    map = "Карта",
    submit = "Сдать",
    leads = "Рейтинг",
    profile = "Профиль",
    login = "Войти",
    splashTagline = "Сдавайте • Отслеживайте • Растите",
    splashExperience = "ЭКО-СОЗНАТЕЛЬНЫЙ ЦИФРОВОЙ ОПЫТ",
    registerNow = "Регистрация",
    createAccount = "Создать аккаунт",
    forgotPassword = "Забыли пароль?",
    welcomeBack = "С возвращением",
    signInSubtitle = "Войдите, чтобы продолжить эко-путь",
    emailAddress = "Email адрес",
    password = "Пароль",
    continueWithGoogle = "Продолжить с Google",
    or = "или",
    noAccountPrefix = "Нет аккаунта? ",
    fullName = "Полное имя",
    joinCommunity = "Присоединяйтесь к эко-сообществу",
    confirmPassword = "Подтвердите пароль",
    fairlyStrongPassword = "Достаточно надежный пароль",
    termsPrefix = "Я принимаю ",
    terms = "Условия сервиса",
    termsAnd = " и ",
    privacyPolicy = "Политику конфиденциальности.",
    orSignUpWith = "ИЛИ ЗАРЕГИСТРИРУЙТЕСЬ ЧЕРЕЗ",
    alreadyHaveAccount = "Уже есть аккаунт? ",
    checkYourEmail = "Проверьте почту",
    forgotPasswordSubtitle = "Введите email, и мы отправим безопасную ссылку для сброса пароля.",
    resetInstructions = { "Мы отправили инструкцию по сбросу пароля на $it." },
    rememberedPassword = "Вспомнили пароль? ",
    sendResetLink = "Отправить ссылку",
    resetLinkSent = "Ссылка отправлена",
    invalidEmail = "Введите корректный email",
    hello = { "Привет, $it!" },
    quickActions = "БЫСТРЫЕ ДЕЙСТВИЯ",
    currentEcoRating = "ТЕКУЩИЙ ЭКО-РЕЙТИНГ",
    points = { "$it баллов" },
    pointsLabel = "Баллы",
    level = { "Уровень $it" },
    globalRank = { "  Общий рейтинг: #$it" },
    virtualTreeTitle = "Ваше виртуальное дерево",
    progressToLevel = { progress, level -> "$progress% до уровня $level" },
    recentAchievements = "Последние достижения",
    searchLocation = "Поиск места...",
    openUntil = "Открыто до 20:00",
    distanceAway = { rating, meters -> " $rating (124)  •  $meters м от вас" },
    acceptedItems = "Принимают",
    reward = "Награда",
    acceptedWasteTypes = "Принимаемые отходы",
    open = "ОТКРЫТО",
    buildRoute = "Построить маршрут",
    call = "Позвонить",
    share = "Поделиться",
    sustainableFact = "Эко-факт",
    submitWaste = "Сдать отходы",
    wasteType = "Тип отходов",
    quantity = "Количество",
    photoConfirmation = "Подтверждение фото",
    takePhotoUpload = "Сделать фото или загрузить",
    commentOptional = "Комментарий (необязательно)",
    addNote = "Добавьте заметку...",
    submitWithPoints = { "Сдать +$it баллов" },
    myEcoTree = "Мое эко-дерево",
    progressToNextLevel = { "Прогресс до уровня $it" },
    xpStatus = { current, next -> "$current / $next XP" },
    xpToGo = { "осталось $it XP" },
    nextGoal = "Следующая цель",
    collectXpGoal = { xp, level -> "Соберите еще $xp XP до уровня $level" },
    growthHistory = "История роста",
    challenges = "Челленджи",
    daily = "Ежедневные",
    weekly = "Еженедельные",
    special = "Особые",
    dailyChallenges = "Ежедневные челленджи",
    weeklyChallenges = "Еженедельные челленджи",
    left = { "осталось $it" },
    active = "Активно",
    completed = "Выполнено",
    locked = "Закрыто",
    ecoSpecialTitle = "Эко-спец: уборка парка",
    ecoSpecialSubtitle = "Присоединяйтесь в субботу и получите двойные баллы!",
    leaderboard = "Рейтинг",
    students = "Студенты",
    faculties = "Факультеты",
    topFaculty = "Лучший факультет",
    thisWeek = { "+$it% за неделю" },
    total = "Всего",
    members = "Участники",
    topContributor = { members, name -> "$members участников • Лидер: $name" },
    memberSince = { "С нами с $it" },
    kgWaste = "кг отходов",
    trees = "Деревья",
    sustainabilityScore = "Индекс устойчивости",
    topContributorText = "Вы в топ 12%\nучастников за\nэтот месяц!",
    nextMilestone = "Следующая цель: уровень 5",
    myAchievements = "Мои достижения",
    recyclingHistory = "История переработки",
    notifications = "Уведомления",
    settings = "Настройки",
    support = "Поддержка",
    logout = "Выйти",
    all = "Все",
    achievements = "Достижения",
    ecoProgress = "Эко-прогресс",
    achievementsUnlocked = { unlocked, total -> "Открыто $unlocked из $total достижений" },
    completePercent = { "$it% выполнено" },
    recentSubmissions = "Последние сдачи",
    yourImpact = "Ваш вклад",
    impactSubtitle = "Следите, что вы сдали и сколько баллов получили.",
    recentNotifications = "Последние уведомления",
    unread = { "$it непрочитано" },
    totalUpdates = { "Всего обновлений: $it" },
    markAllRead = "Прочитать все",
    supportHeroTitle = "EcoDala поддержка Казахстан",
    supportHeroSubtitle = "Поможем с баллами, пунктами переработки и вопросами по приложению.",
    contactUs = "Связаться с нами",
    sendRequest = "Отправить запрос",
    describeIssue = "Опишите проблему...",
    requestSaved = "Запрос сохранен. Поддержка скоро свяжется с вами.",
    faq = "FAQ",
    settingsPreferences = "Предпочтения",
    settingsPushNotifications = "Push-уведомления",
    settingsPushNotificationsSubtitle = "Ежедневные челленджи и награды",
    settingsLocation = "Геолокация",
    settingsLocationSubtitle = "Показывать ближайшие пункты переработки",
    settingsAiTips = "AI эко-советы",
    settingsAiTipsSubtitle = "Персональные подсказки по сортировке",
    settingsDisplayUnits = "Экран и единицы",
    settingsDarkMode = "Темная тема",
    settingsDarkModeSubtitle = "Мгновенно меняет тему приложения",
    settingsLanguage = "Язык",
    settingsLanguageSubtitle = "Выберите язык приложения",
    settingsPreferredUnit = "Единица измерения",
    settingsPreferredUnitSubtitle = "Для сдачи отходов и истории",
    settingsPrivacy = "Приватность",
    settingsPublicProfile = "Публичный профиль в рейтинге",
    settingsPublicProfileSubtitle = "Показывать ваше имя в рейтингах",
    settingsDataSecurity = "Данные и безопасность",
    settingsDataSecuritySubtitle = "Защита аккаунта и экспорт данных",
    settingsInfo = "Настройки сохраняются локально через DataStore, позже можно синхронизировать с backend.",
    wasteTypeName = {
        when (it) {
            WasteType.Plastic -> "Пластик"
            WasteType.Paper -> "Бумага"
            WasteType.Glass -> "Стекло"
            WasteType.Batteries -> "Батарейки"
            WasteType.Electronics -> "Электроника"
            WasteType.Organic -> "Органика"
            WasteType.Metal -> "Металл"
        }
    },
    challengeTypeName = {
        when (it) {
            ChallengeType.Daily -> "Ежедневные"
            ChallengeType.Weekly -> "Еженедельные"
            ChallengeType.Special -> "Особые"
        }
    },
    challengeStatusName = {
        when (it) {
            ChallengeStatus.Active -> "Активно"
            ChallengeStatus.Completed -> "Выполнено"
            ChallengeStatus.Locked -> "Закрыто"
        }
    }
)

private val kazakhEcoStrings = englishEcoStrings.copy(
    languageTag = "kk",
    home = "Басты",
    map = "Карта",
    submit = "Тапсыру",
    leads = "Рейтинг",
    profile = "Профиль",
    login = "Кіру",
    splashTagline = "Тапсыру • Бақылау • Өсу",
    splashExperience = "ЭКО-САНАЛЫ ЦИФРЛЫҚ ТӘЖІРИБЕ",
    registerNow = "Тіркелу",
    createAccount = "Аккаунт ашу",
    forgotPassword = "Құпиясөз ұмытылды ма?",
    welcomeBack = "Қайта қош келдіңіз",
    signInSubtitle = "Эко сапарыңызды жалғастыру үшін кіріңіз",
    emailAddress = "Email мекенжайы",
    password = "Құпиясөз",
    continueWithGoogle = "Google арқылы жалғастыру",
    or = "немесе",
    noAccountPrefix = "Аккаунтыңыз жоқ па? ",
    fullName = "Толық аты",
    joinCommunity = "Эко қауымдастыққа қосылыңыз",
    confirmPassword = "Құпиясөзді растау",
    fairlyStrongPassword = "Құпиясөз жеткілікті мықты",
    termsPrefix = "Мен ",
    terms = "Қызмет шарттарын",
    termsAnd = " және ",
    privacyPolicy = "Құпиялылық саясатын қабылдаймын.",
    orSignUpWith = "НЕМЕСЕ АРҚЫЛЫ ТІРКЕЛУ",
    alreadyHaveAccount = "Аккаунтыңыз бар ма? ",
    checkYourEmail = "Поштаны тексеріңіз",
    forgotPasswordSubtitle = "Email енгізіңіз, біз құпиясөзді қалпына келтіру сілтемесін жібереміз.",
    resetInstructions = { "Құпиясөзді қалпына келтіру нұсқаулығы $it мекенжайына жіберілді." },
    rememberedPassword = "Құпиясөзді еске түсірдіңіз бе? ",
    sendResetLink = "Сілтеме жіберу",
    resetLinkSent = "Сілтеме жіберілді",
    invalidEmail = "Дұрыс email енгізіңіз",
    hello = { "Сәлем, $it!" },
    quickActions = "ЖЫЛДАМ ӘРЕКЕТТЕР",
    currentEcoRating = "ҚАЗІРГІ ЭКО-РЕЙТИНГ",
    points = { "$it балл" },
    pointsLabel = "Балл",
    level = { "$it-деңгей" },
    globalRank = { "  Жалпы рейтинг: #$it" },
    virtualTreeTitle = "Виртуалды ағашыңыз",
    progressToLevel = { progress, level -> "$progress% $level-деңгейге дейін" },
    recentAchievements = "Соңғы жетістіктер",
    searchLocation = "Орын іздеу...",
    openUntil = "20:00 дейін ашық",
    distanceAway = { rating, meters -> " $rating (124)  •  $meters м қашық" },
    acceptedItems = "Қабылдайды",
    reward = "Сыйақы",
    acceptedWasteTypes = "Қабылданатын қалдықтар",
    open = "АШЫҚ",
    buildRoute = "Маршрут құру",
    call = "Қоңырау",
    share = "Бөлісу",
    sustainableFact = "Эко-факт",
    submitWaste = "Қалдық тапсыру",
    wasteType = "Қалдық түрі",
    quantity = "Саны",
    photoConfirmation = "Фото растау",
    takePhotoUpload = "Фото түсіру немесе жүктеу",
    commentOptional = "Пікір (міндетті емес)",
    addNote = "Ескертпе қосыңыз...",
    submitWithPoints = { "Тапсыру +$it балл" },
    myEcoTree = "Менің эко-ағашым",
    progressToNextLevel = { "$it-деңгейге дейін прогресс" },
    xpStatus = { current, next -> "$current / $next XP" },
    xpToGo = { "$it XP қалды" },
    nextGoal = "Келесі мақсат",
    collectXpGoal = { xp, level -> "$level-деңгейге жету үшін тағы $xp XP жинаңыз" },
    growthHistory = "Өсу тарихы",
    challenges = "Челлендждер",
    daily = "Күнделікті",
    weekly = "Апталық",
    special = "Арнайы",
    dailyChallenges = "Күнделікті челлендждер",
    weeklyChallenges = "Апталық челлендждер",
    left = { "$it қалды" },
    active = "Белсенді",
    completed = "Аяқталды",
    locked = "Құлыптаулы",
    ecoSpecialTitle = "Эко-арнайы: парк тазалау",
    ecoSpecialSubtitle = "Сенбі күні қосылып, екі есе балл алыңыз!",
    leaderboard = "Рейтинг",
    students = "Студенттер",
    faculties = "Факультеттер",
    topFaculty = "Үздік факультет",
    thisWeek = { "+$it% осы аптада" },
    total = "Барлығы",
    members = "Қатысушылар",
    topContributor = { members, name -> "$members қатысушы • Үздік: $name" },
    memberSince = { "$it бастап қатысушы" },
    kgWaste = "кг қалдық",
    trees = "Ағаштар",
    sustainabilityScore = "Тұрақтылық ұпайы",
    topContributorText = "Сіз осы айдағы\nқатысушылардың\nтоп 12%-ындасыз!",
    nextMilestone = "Келесі мақсат: 5-деңгей",
    myAchievements = "Менің жетістіктерім",
    recyclingHistory = "Қайта өңдеу тарихы",
    notifications = "Хабарламалар",
    settings = "Баптаулар",
    support = "Қолдау",
    logout = "Шығу",
    all = "Барлығы",
    achievements = "Жетістіктер",
    ecoProgress = "Эко-прогресс",
    achievementsUnlocked = { unlocked, total -> "$total жетістіктің $unlocked ашылды" },
    completePercent = { "$it% аяқталды" },
    recentSubmissions = "Соңғы тапсырулар",
    yourImpact = "Сіздің үлесіңіз",
    impactSubtitle = "Не тапсырғаныңызды және қанша балл алғаныңызды бақылаңыз.",
    recentNotifications = "Соңғы хабарламалар",
    unread = { "$it оқылмаған" },
    totalUpdates = { "Барлық жаңарту: $it" },
    markAllRead = "Барлығын оқу",
    supportHeroTitle = "EcoDala Қазақстан қолдауы",
    supportHeroSubtitle = "Балл, қайта өңдеу пункттері және қолданба сұрақтары бойынша көмектесеміз.",
    contactUs = "Бізбен байланысу",
    sendRequest = "Сұрау жіберу",
    describeIssue = "Мәселені сипаттаңыз...",
    requestSaved = "Сұрау сақталды. Қолдау жақында хабарласады.",
    faq = "Жиі сұрақтар",
    settingsPreferences = "Қалаулар",
    settingsPushNotifications = "Push хабарламалар",
    settingsPushNotificationsSubtitle = "Күнделікті челлендждер мен марапаттар",
    settingsLocation = "Геолокация",
    settingsLocationSubtitle = "Жақын қайта өңдеу пункттерін көрсету",
    settingsAiTips = "AI эко-кеңестер",
    settingsAiTipsSubtitle = "Сұрыптау бойынша жеке ұсыныстар",
    settingsDisplayUnits = "Экран және өлшемдер",
    settingsDarkMode = "Қараңғы режим",
    settingsDarkModeSubtitle = "Қолданба тақырыбын бірден ауыстырады",
    settingsLanguage = "Тіл",
    settingsLanguageSubtitle = "Қолданба тілін таңдаңыз",
    settingsPreferredUnit = "Өлшем бірлігі",
    settingsPreferredUnitSubtitle = "Қалдық тапсыруда және тарихта қолданылады",
    settingsPrivacy = "Құпиялылық",
    settingsPublicProfile = "Рейтингтегі ашық профиль",
    settingsPublicProfileSubtitle = "Рейтингтерде атыңызды көрсету",
    settingsDataSecurity = "Деректер және қауіпсіздік",
    settingsDataSecuritySubtitle = "Аккаунтты қорғау және деректерді экспорттау",
    settingsInfo = "Баптаулар DataStore арқылы локалды сақталады, кейін backend-пен синхрондауға болады.",
    wasteTypeName = {
        when (it) {
            WasteType.Plastic -> "Пластик"
            WasteType.Paper -> "Қағаз"
            WasteType.Glass -> "Шыны"
            WasteType.Batteries -> "Батареялар"
            WasteType.Electronics -> "Электроника"
            WasteType.Organic -> "Органика"
            WasteType.Metal -> "Металл"
        }
    },
    challengeTypeName = {
        when (it) {
            ChallengeType.Daily -> "Күнделікті"
            ChallengeType.Weekly -> "Апталық"
            ChallengeType.Special -> "Арнайы"
        }
    },
    challengeStatusName = {
        when (it) {
            ChallengeStatus.Active -> "Белсенді"
            ChallengeStatus.Completed -> "Аяқталды"
            ChallengeStatus.Locked -> "Құлыптаулы"
        }
    }
)
